server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:inventorydb}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true